import { test, expect, type APIRequestContext, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'
import path from 'node:path'

/**
 * E2E for the admin-only TLS / HTTPS settings page (`TlsSettingsSection`,
 * routes in `routes/settings.rs`). Reuses the running server's own
 * self-signed pair at `${PECKBOARD_E2E_DATA_DIR}/certs/{cert,key}.pem` as
 * the "valid uploaded certificate" fixture — it's a real cert/key pair
 * `rustls` accepts, with no openssl dependency in the test.
 */

const ADMIN_USER = 'e2e-user'
const ADMIN_PASS = 'e2e-password-1234'

type Auth = { token: string; auth: Record<string, string> }

type TlsStatus = {
  https_enabled: boolean
  https_port: number
  source: 'uploaded' | 'self-signed' | 'none'
  sans: string[]
  not_after?: string | null
  error?: string | null
}

async function authenticate(request: APIRequestContext): Promise<Auth> {
  const res = await request.post('/api/auth/login', {
    data: { username: ADMIN_USER, password: ADMIN_PASS },
  })
  expect(res.ok(), `login failed: ${await res.text()}`).toBeTruthy()
  const { token } = (await res.json()) as { token: string }
  return { token, auth: { Authorization: `Bearer ${token}` } }
}

async function createNonAdmin(
  request: APIRequestContext,
  adminAuth: Record<string, string>,
  suffix: string,
): Promise<Auth> {
  const username = `tls-test-${suffix}-${Date.now()}`
  const password = 'tls-password-1234'
  const created = await request.post('/api/users', {
    headers: adminAuth,
    data: { username, password, role: 'user' },
  })
  expect(created.ok(), `create user failed: ${await created.text()}`).toBeTruthy()
  const res = await request.post('/api/auth/login', { data: { username, password } })
  expect(res.ok(), `login as ${username} failed: ${await res.text()}`).toBeTruthy()
  const { token } = (await res.json()) as { token: string }
  return { token, auth: { Authorization: `Bearer ${token}` } }
}

async function getTlsStatus(
  request: APIRequestContext,
  auth: Record<string, string>,
): Promise<TlsStatus> {
  const res = await request.get('/api/settings/tls', { headers: auth })
  expect(res.ok(), `get tls status failed: ${await res.text()}`).toBeTruthy()
  return (await res.json()) as TlsStatus
}

/** Plant a token, open the Settings hub, and navigate to the TLS sub-page. */
async function openTlsSettings(page: Page, token: string) {
  await page.addInitScript((t) => {
    localStorage.setItem('peckboard_token', t)
  }, token)
  await page.goto('/settings')
  await expect(page.getByTestId('settings-page')).toBeVisible({ timeout: 10_000 })
  await page.getByTestId('settings-nav-tls').click()
  await expect(page.getByTestId('tls-settings-section')).toBeVisible({ timeout: 10_000 })
}

test.describe('TLS settings page', () => {
  test('a non-admin does not see the TLS nav entry; an admin does', async ({ request, page }) => {
    const { auth: adminAuth, token: adminToken } = await authenticate(request)
    const { token: userToken } = await createNonAdmin(request, adminAuth, 'gate')

    await page.addInitScript((t) => {
      localStorage.setItem('peckboard_token', t)
    }, userToken)
    await page.goto('/settings')
    await expect(page.getByTestId('settings-page')).toBeVisible({ timeout: 10_000 })
    await expect(page.getByTestId('settings-nav-tls')).toHaveCount(0)

    // Same hub as the admin does show it — the gate is role-driven.
    await openTlsSettings(page, adminToken)
  })

  test('the status block renders source, port, and expiry', async ({ request, page }) => {
    const { auth, token } = await authenticate(request)
    const status = await getTlsStatus(request, auth)

    await openTlsSettings(page, token)

    const httpsText = status.https_enabled
      ? `Enabled on port ${status.https_port}`
      : 'Disabled — serving HTTP only'
    await expect(page.getByTestId('tls-status-https')).toHaveText(httpsText)

    const sourceLabel =
      status.source === 'uploaded'
        ? 'Uploaded certificate'
        : status.source === 'self-signed'
          ? 'Self-signed (generated by PeckBoard)'
          : 'None'
    await expect(page.getByTestId('tls-status-source')).toHaveText(sourceLabel)

    if (status.not_after) {
      await expect(page.getByTestId('tls-status-expiry')).toBeVisible()
      await expect(page.getByTestId('tls-status-expiry')).not.toHaveText('')
    }
  })

  test('the covered hostnames/IPs list includes localhost and 127.0.0.1', async ({
    request,
    page,
  }) => {
    const { token } = await authenticate(request)
    await openTlsSettings(page, token)

    const list = page.getByTestId('tls-san-list')
    await expect(list).toBeVisible()
    await expect(list).toContainText('localhost')
    await expect(list).toContainText('127.0.0.1')
  })

  test('regenerate goes through the confirm dialog and the page reflects a new expiry', async ({
    request,
    page,
  }) => {
    const { auth, token } = await authenticate(request)
    const before = await getTlsStatus(request, auth)

    await openTlsSettings(page, token)
    await page.getByTestId('tls-regenerate-btn').click()
    await expect(page.getByTestId('tls-regenerate-confirm')).toBeVisible()
    await page.getByTestId('confirm-dialog-confirm').click()
    await expect(page.getByTestId('tls-regenerate-confirm')).toHaveCount(0, { timeout: 10_000 })

    await expect
      .poll(async () => (await getTlsStatus(request, auth)).not_after)
      .not.toBe(before.not_after)
  })

  test('uploading a malformed certificate shows the server error inline and does not change the active certificate', async ({
    request,
    page,
  }) => {
    const { auth, token } = await authenticate(request)
    const before = await getTlsStatus(request, auth)

    await openTlsSettings(page, token)
    await page.getByTestId('tls-upload-cert-input').fill('not a certificate')
    await page.getByTestId('tls-upload-key-input').fill('not a key')
    await page.getByTestId('tls-upload-btn').click()

    await expect(page.getByTestId('tls-upload-error')).toBeVisible({ timeout: 10_000 })
    await expect(page.getByTestId('tls-upload-error')).toContainText('certificate')

    const after = await getTlsStatus(request, auth)
    expect(after.source).toBe(before.source)
    expect(after.not_after).toBe(before.not_after)
  })

  test('uploading a valid self-signed pair flips the source to uploaded and reveals revert', async ({
    request,
    page,
  }) => {
    const { auth, token } = await authenticate(request)
    const dataDir = process.env.PECKBOARD_E2E_DATA_DIR
    if (!dataDir) throw new Error('PECKBOARD_E2E_DATA_DIR is not set for this run')
    // The server's own self-signed pair: a real cert/key rustls accepts,
    // uploaded back at itself just to exercise the "uploaded" source path.
    const certPem = readFileSync(path.join(dataDir, 'certs', 'cert.pem'), 'utf8')
    const keyPem = readFileSync(path.join(dataDir, 'certs', 'key.pem'), 'utf8')

    try {
      await openTlsSettings(page, token)
      await page.getByTestId('tls-upload-cert-input').fill(certPem)
      await page.getByTestId('tls-upload-key-input').fill(keyPem)
      await page.getByTestId('tls-upload-btn').click()

      await expect(page.getByTestId('tls-status-source')).toHaveText('Uploaded certificate', {
        timeout: 10_000,
      })
      await expect(page.getByTestId('tls-revert-section')).toBeVisible()

      await page.getByTestId('tls-revert-btn').click()
      await expect(page.getByTestId('tls-revert-confirm')).toBeVisible()
      await page.getByTestId('confirm-dialog-confirm').click()
      await expect(page.getByTestId('tls-status-source')).toHaveText(
        'Self-signed (generated by PeckBoard)',
        { timeout: 10_000 },
      )
    } finally {
      // Best-effort: restore self-signed if an assertion above threw
      // mid-flow, so later specs (and re-runs) see a clean state.
      await request.delete('/api/settings/tls/cert', { headers: auth })
    }
  })
})
