import { useEffect, useRef, useState } from 'react'
import { readFileAsText } from '../lib/readFileAsText'
import { authedFetch } from '../store/auth'
import type { TlsStatus } from '../types/api'
import ConfirmDialog from './ConfirmDialog'
import FieldError from './FieldError'

function formatExpiry(at: string): string {
  const d = new Date(at)
  return isNaN(d.getTime()) ? at : d.toLocaleString()
}

/**
 * Admin-only TLS management: what certificate the HTTPS listener is
 * serving, which addresses it covers, and the three ways to change it
 * (regenerate the self-signed cert, upload an operator pair, revert to
 * self-signed). Backed by `/api/settings/tls*` in `routes/settings.rs`.
 *
 * The uploaded private key lives in component state only while the form
 * is being filled and is cleared the moment the server accepts it — the
 * status endpoint never returns key material, so nothing echoes it back.
 */
export default function TlsSettingsSection() {
  const [status, setStatus] = useState<TlsStatus | null>(null)
  const [loadError, setLoadError] = useState<string | null>(null)

  const [confirming, setConfirming] = useState<'regenerate' | 'revert' | null>(null)
  const [actionBusy, setActionBusy] = useState(false)
  const [actionError, setActionError] = useState<string | null>(null)

  const [certPem, setCertPem] = useState('')
  const [keyPem, setKeyPem] = useState('')
  const [uploading, setUploading] = useState(false)
  const [uploadError, setUploadError] = useState<string | null>(null)
  const [uploadDone, setUploadDone] = useState(false)
  const certFileRef = useRef<HTMLInputElement>(null)
  const keyFileRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    let cancelled = false
    authedFetch('/api/settings/tls')
      .then((res) => res.json().then((data) => ({ ok: res.ok, data })))
      .then(({ ok, data }) => {
        if (cancelled) return
        if (!ok) throw new Error('bad status')
        setStatus(data as TlsStatus)
      })
      .catch(() => {
        if (cancelled) return
        setLoadError('Could not load the TLS status.')
      })
    return () => {
      cancelled = true
    }
  }, [])

  /** Shared tail for the two confirmed actions: both endpoints answer
   *  with the fresh status on success and `{ error }` on failure. */
  const runConfirmed = async (path: string, method: string) => {
    setActionBusy(true)
    setActionError(null)
    try {
      const res = await authedFetch(path, { method })
      const data = (await res.json().catch(() => null)) as (TlsStatus & { error?: string }) | null
      if (!res.ok) throw new Error(data?.error || `HTTP ${res.status}`)
      if (data) setStatus(data)
      setConfirming(null)
    } catch (e) {
      setActionError(e instanceof Error ? e.message : 'Request failed')
    } finally {
      setActionBusy(false)
    }
  }

  const pickFile = async (e: React.ChangeEvent<HTMLInputElement>, set: (pem: string) => void) => {
    const file = e.target.files?.[0]
    e.target.value = ''
    if (!file) return
    setUploadError(null)
    setUploadDone(false)
    try {
      set(await readFileAsText(file))
    } catch {
      setUploadError(`Could not read ${file.name}.`)
    }
  }

  const upload = async () => {
    setUploading(true)
    setUploadError(null)
    setUploadDone(false)
    try {
      const res = await authedFetch('/api/settings/tls/cert', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ cert_pem: certPem, key_pem: keyPem }),
      })
      const data = (await res.json().catch(() => null)) as (TlsStatus & { error?: string }) | null
      if (!res.ok) throw new Error(data?.error || `HTTP ${res.status}`)
      // Success: drop the key material from the DOM immediately.
      setCertPem('')
      setKeyPem('')
      setUploadDone(true)
      if (data) setStatus(data)
    } catch (e) {
      setUploadError(e instanceof Error ? e.message : 'Upload failed')
    } finally {
      setUploading(false)
    }
  }

  const sourceLabel =
    status?.source === 'uploaded'
      ? 'Uploaded certificate'
      : status?.source === 'self-signed'
        ? 'Self-signed (generated by PeckBoard)'
        : 'None'

  return (
    <>
      <section className="settings-section" data-testid="tls-settings-section">
        <h3>TLS / HTTPS</h3>
        <p className="form-hint">
          The self-signed certificate covers every address this host had when it was generated,
          which removes the browser&apos;s name-mismatch error — but browsers still warn that a
          self-signed certificate is untrusted. Only a certificate from a trusted authority removes
          the warning entirely.
        </p>

        {loadError && (
          <p className="form-error" role="alert" data-testid="tls-settings-error">
            {loadError}
          </p>
        )}

        {status === null && !loadError && <p className="settings-loading">Loading TLS status...</p>}

        {status && (
          <>
            {status.error && (
              <p className="form-error" role="alert" data-testid="tls-startup-error">
                HTTPS failed at startup and the server fell back to HTTP only: {status.error}
              </p>
            )}
            <div className="settings-info-grid">
              <div className="settings-row">
                <span className="settings-label">HTTPS</span>
                <span data-testid="tls-status-https">
                  {status.https_enabled
                    ? `Enabled on port ${status.https_port}`
                    : 'Disabled — serving HTTP only'}
                </span>
              </div>
              <div className="settings-row">
                <span className="settings-label">Certificate</span>
                <span data-testid="tls-status-source">{sourceLabel}</span>
              </div>
              {status.not_after && (
                <div className="settings-row">
                  <span className="settings-label">Expires</span>
                  <span data-testid="tls-status-expiry">{formatExpiry(status.not_after)}</span>
                </div>
              )}
            </div>
          </>
        )}
      </section>

      {status && (
        <section className="settings-section" data-testid="tls-san-section">
          <h3>Covered hostnames &amp; IPs</h3>
          <p className="form-hint">
            The addresses this certificate is valid for. The list is snapshotted when the
            certificate is generated, so if this machine joins a new network, regenerate below to
            cover the new address.
          </p>
          {status.sans.length === 0 ? (
            <p className="settings-loading">The current certificate lists no addresses.</p>
          ) : (
            <ul className="tls-san-list" data-testid="tls-san-list">
              {status.sans.map((san) => (
                <li className="tls-san" key={san}>
                  {san}
                </li>
              ))}
            </ul>
          )}
        </section>
      )}

      {status && (
        <section className="settings-section" data-testid="tls-regenerate-section">
          <h3>Regenerate self-signed certificate</h3>
          <p className="form-hint">
            Issues a fresh self-signed certificate covering the addresses this host has right now,
            including any gained since the server started.
            {status.source === 'uploaded' &&
              ' Your uploaded certificate stays active — this only refreshes the self-signed fallback.'}
          </p>
          <div className="settings-row">
            <button
              type="button"
              className="btn-secondary"
              onClick={() => {
                setActionError(null)
                setConfirming('regenerate')
              }}
              data-testid="tls-regenerate-btn"
            >
              Regenerate certificate
            </button>
          </div>
        </section>
      )}

      {status && (
        <section className="settings-section" data-testid="tls-upload-section">
          <h3>Upload a certificate</h3>
          <p className="form-hint">
            Install a certificate and private key of your own — for example one issued for this
            host&apos;s DNS name by a trusted authority, which is the only way to remove the browser
            warning. Pick a PEM file or paste the PEM text.
          </p>
          <div className="tls-upload-field">
            <label htmlFor="tls-cert-pem">
              <span className="settings-label">Certificate (PEM)</span>
            </label>
            <textarea
              id="tls-cert-pem"
              className="tls-pem-input"
              placeholder="-----BEGIN CERTIFICATE-----"
              value={certPem}
              spellCheck={false}
              onChange={(e) => {
                setUploadDone(false)
                setCertPem(e.target.value)
              }}
              data-testid="tls-upload-cert-input"
            />
            <input
              ref={certFileRef}
              type="file"
              accept=".pem,.crt,.cer,.txt"
              hidden
              onChange={(e) => void pickFile(e, setCertPem)}
              data-testid="tls-upload-cert-file"
            />
            <button
              type="button"
              className="btn-secondary"
              onClick={() => certFileRef.current?.click()}
            >
              Choose certificate file…
            </button>
          </div>
          <div className="tls-upload-field">
            <label htmlFor="tls-key-pem">
              <span className="settings-label">Private key (PEM)</span>
            </label>
            <textarea
              id="tls-key-pem"
              className="tls-pem-input"
              placeholder="-----BEGIN PRIVATE KEY-----"
              value={keyPem}
              spellCheck={false}
              onChange={(e) => {
                setUploadDone(false)
                setKeyPem(e.target.value)
              }}
              data-testid="tls-upload-key-input"
            />
            <input
              ref={keyFileRef}
              type="file"
              accept=".pem,.key,.txt"
              hidden
              onChange={(e) => void pickFile(e, setKeyPem)}
              data-testid="tls-upload-key-file"
            />
            <button
              type="button"
              className="btn-secondary"
              onClick={() => keyFileRef.current?.click()}
            >
              Choose key file…
            </button>
          </div>
          <FieldError message={uploadError ?? undefined} testId="tls-upload-error" />
          <div className="settings-row">
            <button
              type="button"
              className="btn-secondary"
              onClick={() => void upload()}
              disabled={uploading || !certPem.trim() || !keyPem.trim()}
              data-testid="tls-upload-btn"
            >
              {uploading ? 'Installing…' : 'Install certificate'}
            </button>
            {uploadDone && <span className="form-hint">Certificate installed.</span>}
          </div>
        </section>
      )}

      {status?.source === 'uploaded' && (
        <section className="settings-section" data-testid="tls-revert-section">
          <h3>Revert to self-signed</h3>
          <p className="form-hint">
            Remove the uploaded certificate and serve the self-signed one again.
          </p>
          <div className="settings-row">
            <button
              type="button"
              className="btn-secondary"
              onClick={() => {
                setActionError(null)
                setConfirming('revert')
              }}
              data-testid="tls-revert-btn"
            >
              Revert to self-signed
            </button>
          </div>
        </section>
      )}

      {confirming === 'regenerate' && (
        <ConfirmDialog
          testId="tls-regenerate-confirm"
          danger
          title="Regenerate the self-signed certificate?"
          message="A new certificate is issued covering the IP addresses this host has right now — including any gained since the server booted. The current self-signed certificate stops working immediately, so anything that pinned or trusted it must accept the new one. Browsers will still show the untrusted-certificate warning; regenerating only fixes which addresses the certificate covers."
          confirmLabel="Regenerate"
          busy={actionBusy}
          busyLabel="Regenerating…"
          error={actionError}
          onConfirm={() => void runConfirmed('/api/settings/tls/regenerate', 'POST')}
          onCancel={() => setConfirming(null)}
        />
      )}

      {confirming === 'revert' && (
        <ConfirmDialog
          testId="tls-revert-confirm"
          danger
          title="Revert to the self-signed certificate?"
          message="The uploaded certificate and its private key are removed and the server goes back to serving its self-signed certificate. Browsers will warn that it is untrusted again."
          confirmLabel="Revert"
          busy={actionBusy}
          busyLabel="Reverting…"
          error={actionError}
          onConfirm={() => void runConfirmed('/api/settings/tls/cert', 'DELETE')}
          onCancel={() => setConfirming(null)}
        />
      )}
    </>
  )
}
